import assert from 'node:assert/strict';
import { SCHOOL_YEARS } from '../src/data/schoolYears';
import { displayEventTitle, eventClassNames, getCycleInfo, schoolYearToIcs, upcomingEvents } from '../src/lib/calendar';
const prep = SCHOOL_YEARS.find(x => x.id === '2026-2027-prep')!;
const high = SCHOOL_YEARS.find(x => x.id === '2026-2027-high')!;
const term = prep.terms[0];
const find = (id: string) => term.events.find(x => x.id === `prep-2026-${id}`)!;
assert.equal(term.events.length,132);
assert.equal(term.events.filter(x=>x.category==='cycle').length,119);
assert.equal(term.notices?.length,3);
assert.equal(find('midautumn').endDate,'2026-09-26');
assert.equal(find('national').endDate,'2026-10-05');
assert.equal(find('oct-exam').date,'2026-10-06');
assert.equal(find('oct-exam').endDate,'2026-10-07');
assert.equal(find('midterm').date,'2026-11-03');
assert.equal(find('final').date,'2027-01-12');
assert.equal(find('winter').date,'2027-01-31');
assert.equal(find('winter').endDate,'2027-02-14');
assert.equal(find('return').date,'2027-02-15');
assert(!term.events.some(x=>x.date>='2027-02-16' && x.date<='2027-02-22'));
const saturday=find('cycle-2026-09-05');
assert.equal(getCycleInfo(saturday)?.letter,'F');
assert.equal(getCycleInfo(saturday)?.circle,'');
assert(!eventClassNames(saturday).includes('event-cycle-adjusted'));
assert(eventClassNames(find('cycle-2026-09-27')).includes('event-cycle-adjusted'));
assert.equal(displayEventTitle(find('cycle-2026-11-02')),'答疑C');
assert.equal(displayEventTitle(find('cycle-2027-01-11')),'答疑D');
assert(!upcomingEvents(term,'2026-09-01',100).some(x=>x.id===saturday.id));
assert(upcomingEvents(term,'2026-09-01',100).some(x=>x.title==='答疑C'));
const ics=schoolYearToIcs(prep);
assert.equal((ics.match(/BEGIN:VEVENT/g)||[]).length,13);
assert.match(ics,/DTSTART;VALUE=DATE:20270131\r\nDTEND;VALUE=DATE:20270215/);
assert.match(ics,/DTSTART;VALUE=DATE:20261006\r\nDTEND;VALUE=DATE:20261008/);
assert(!ics.includes('具体日期待定'));
assert.equal(new Set([...ics.matchAll(/UID:(.+)/g)].map(x=>x[1])).size,13);
assert.equal(high.terms[0].events.length,125);
assert.equal(high.terms[0].events.find(x=>x.title==='国庆节假期')?.endDate,'2026-10-07');
assert.equal(SCHOOL_YEARS.filter(x=>x.yearId!=='2026-2027').length,4);
console.log('PASS: prep source anchors, 119 cycles, blank dates, ordinary Saturday, consultation, inclusive ICS ranges, unique UIDs, and existing calendars.');
